### ISSUE TITLE
Add Event proposal button

### ISSUE THREAD

**Issue by Mizkoeu** [GrinnellAppDev/Grinnell-Events-iOS#29]
User may have the option to suggest/publicize events from within the app. The request will be submitted to the backend, before the admin approves or rejects the new addition.
This task may require multiple components:
1. Design and add the frontend UI --> button + new View Controller design
2. Do we require login for authentication? or simply make it anonymous?
3. Mock up the backend for testing.

**Comment by licherie** [comment]
Currently viewDidLoad() is called again when clicking on the (placeholder0 button. I found this for explanation: https://stackoverflow.com/questions/11969452/viewdidload-is-in-fact-called-every-time-there-is-a-segue-transition 

I didn't notice this before since there are no other segue buttons (that are not bar buttons) in the app. I'm thinking to fix this because I think it's inefficient to have the view loaded again when it doesn't need to be.

**Comment by licherie** [comment]
Ah ok i see , we were subclassing viewcontroller
Not uiviewcontroller 😭😭😭😭

**Comment by licherie** [comment]
Issues/Features to add: 

*Fix event time sorting: Right now time and date are correct but within each day sometimes events happening at 7:00 p.m. are sorted before events happening at 10:00 a.m. the same day. 

*Add function for the Submit button 

*Change layout to Grace's changes 

*add other user-friendly textfield functions like highlighting selected text field etc. 
https://uxplanet.org/designing-perfect-text-field-clarity-accessibility-and-user-effort-d03c1e26004b

*Make backend if time permits loooll
